server:
  port: 8088

spring:

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: "*"

            value:
              default:
                type: com.ecommerce.common_kafka_models.dto.NotificationEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: srinivasraju.jvrs@gmail.com
    password: knglukdogmwflaxr

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true