server:
  port: 8087

spring:
  application:
    name: saga-orchestrator

  kafka:
    bootstrap-servers: localhost:9092   # ✅ REQUIRED

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    consumer:
      group-id: saga-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

        # 🔥 THIS IS THE FIX
        spring.json.value.default.type: com.ecommerce.common_kafka_models.dto.StockSuccessEvent